project:
  type: website

website:
  title: "Environment notes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: extras.qmd
        text: Extras

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



